[package]
name = "agent-burn-windows"
version = "0.1.17"
description = "Agent Burn Windows Desktop Application"
edition = "2021"

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "process"] }
winreg = "0.52"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
sqlite = { version = "0.37.0", default-features = false, features = ["bundled", "linkage"] }

[build-dependencies]
tauri-build = { version = "2", default-features = false , features = [] }
